theme = "tokyonight_storm"

[editor]
line-number = "relative"
cursorline = true
rulers = [80]

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

############################################
### NORMAL MODE
###########################################

[keys.normal]

# Esc extended
esc = ["collapse_selection", "normal_mode"]

# Repat last motion ( next )
"C-n" = ["repeat_last_motion"]

# Go down by 5 lines.
"C-j"= ["goto_line_start", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]

# Go up by 5 lines.
"C-k"= ["goto_line_start", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]

# Scroll down view by 5 lines
"C-e" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Scroll up view by 5 lines
"C-y" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]

# Move line down
"down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Move line up
"up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# VIM cursor align one key.
"H" = "goto_window_top"
"L" = "goto_window_bottom"
"M" = "goto_window_center"

# muscle memory from vim.

# Vertical Multicursor.
"C-v" = "copy_selection_on_next_line"

# Add change to the end of line. ( old veetical multicursor )
"C" = ["select_mode", "goto_line_end", "change_selection"]

# Delete to the end of line.
"D" = ["select_mode", "goto_line_end", "delete_selection"]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
"%" = "match_brackets"
"s" = ["change_selection"]
"i" = ["insert_mode", "collapse_selection"]
"a" = ["append_mode", "collapse_selection"]

# native line select is replaced by V
"x" = ["delete_selection"]


############################################
### SELECT MODE
###########################################

[keys.select]

# Move line down
"down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Move line up
"up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Scroll down view by 5 lines
"C-e" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Scroll up view by 5 lines
"C-y" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]

# Repat last motion ( next )
"C-n" = ["repeat_last_motion"]

# Paste without delete the content.
p = "replace_with_yanked"
P = "replace_selections_with_clipboard"

# muscle memory from vim.
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

############################################
### SELECT G MODE
###########################################

[keys.select.g]

# muscle memory from vim.
"_" = "goto_line_end"
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
