theme = "nord"

[editor]
line-number = "relative"
cursorline = true
rulers = [80]

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true


############################################
### NORMAL MODE
###########################################

[keys.normal]

# Escape
"esc" = ["collapse_selection", "normal_mode"]

# Repat last motion ( next )
"C-n" = ["repeat_last_motion"]

# Go down by 5 lines.
"C-j"= ["goto_line_start", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]

# Go up by 5 lines.
"C-k"= ["goto_line_start", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]

# Scroll down view by 5 lines
"C-e" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Scroll up view by 5 lines
"C-y" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]

# Move line down
"down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Move line up
"up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# treeseter selection
"+" = "expand_selection"
"_" = "shrink_selection"
"}" = "select_next_sibling"
"{" = "select_prev_sibling"

# Switch vertical multicursor from Shift to Ctrl.
"C-v" = "copy_selection_on_next_line"

# Add change from cursor to the end of line. ( old veretical multicursor command )
"C" = ["collapse_selection", "select_mode", "goto_line_end", "change_selection"]

# Delete from cursor to the end of line.
"D" = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]

# Muscle memory from vim fallback.
# Will be remove as soon
"0" = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"G" = "goto_file_end"
"V" = ["select_mode", "extend_to_line_bounds"]





############################################
### NORMAL MODE G
###########################################

[keys.normal.g]

# Muscle memory from vim fallback.
# Will be remove as soon
"0" = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"




############################################
### SELECT MODE
###########################################

[keys.select]

# Escape
"esc" = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Move line down
"down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Move line up
"up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Scroll down view by 5 lines
"C-e" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Scroll up view by 5 lines
"C-y" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]

# Repat last motion ( next )
"C-n" = ["repeat_last_motion"]

# Make selecting lines in visual mode behave sensibly
"k" = ["extend_line_up", "extend_to_line_bounds"]
"j" = ["extend_line_down", "extend_to_line_bounds"]

# treeseter selection
"+" = "expand_selection"
"_" = "shrink_selection"
"}" = "select_next_sibling"
"{" = "select_prev_sibling"

# Muscle memory from vim fallback.
# Will be remove as soon
"0" = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"G" = "goto_file_end"


############################################
### SELECT G MODE
###########################################

[keys.select.g]

# Muscle memory from vim fallback.
# Will be remove as soon
"0" = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
