theme = "tokyonight_storm"

[editor]
line-number = "relative"
cursorline = true
rulers = [80]

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[keys.normal]

# Esc extended
esc = ["collapse_selection", "normal_mode"]

# Repat last motion ( next )
"C-n" = ["repeat_last_motion"]

# Go down by 5 lines.
"C-j"= ["goto_line_start", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]

# Go up by 5 lines.
"C-k"= ["goto_line_start", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]

# Scroll down view by 5 lines
"C-e" = ["scroll_down", "scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Scroll up view by 5 lines
"C-y" = ["scroll_up", "scroll_up", "scroll_up", "scroll_up", "scroll_up"]

# Move line down
"down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]

# Move line up
"up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
