# npm i -g vscode-langservers-extracted
# npm install -g typescript-language-server typescript
# npm install -g prettier
# npm install -g eslint
# npm install -g stylelint

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "scss"
formatter = { command = 'prettier', args = ["--parser", "css"] }
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
indent = { tab-width = 4, unit = "  " }
